[package]
name = "rvm_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
rand = "0.6"
rust-crypto = "0.2.36"
serde_json = "1.0.96"
